name: Multiple OS CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
  deploy:
    name: Deploy on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Deploy to server
      run: |
        echo "Deploying application on ${{ matrix.os }}..."
        # Add your deployment commands here

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
    - name: Send notification
      run: |
        echo "Sending notification to the team..."
        # Add your notification commands here (e.g., Slack, email)

  cleanup:
    name: Cleanup Resources 
    runs-on: ubuntu-latest
    needs: notify
    if: always()
    steps:
    - name: Cleanup
      run: |
        echo "Cleaning up resources..."
        # Add your cleanup commands here
