name: Tag and Label Pull Requests
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: [ main ]
jobs:
  tag-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tag and label PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'reviewed, needs-testing'
          remove_labels: 'in-progress'
          tag_prefix: 'pr-'
          tag_suffix: ''
          tag_on: 'opened,synchronize,reopened,labeled,unlabeled'
          tag_message: 'Tagging PR #${{ github.event.number }}'
          tag_force: true
          tag_annotate: false
          tag_create_release: false
          tag_release_name: 'Release for PR #${{ github.event.number }}'
          tag_release_body: 'This release corresponds to PR #${{ github.event.number }}'