name: Label Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
  push:
    branches: [ main ]

    
permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'needs review' label to PR
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs review 
          only_labels: ''
          remove_labels: ''
          issue_number: ${{ github.event.pull_request.number }}
